{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template  "wordpress.fullname" . }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/{{ template  "wordpress.fullname" . }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template  "wordpress.fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}