apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wordpress.fullname" . }}
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  WORDPRESS_DB_HOST: {{ .Values.WORDPRESS_DB_HOST | b64enc | quote }}
  WORDPRESS_DB_NAME: {{ .Values.WORDPRESS_DB_NAME | b64enc | quote }}
  WORDPRESS_DB_USER: {{ .Values.WORDPRESS_DB_USER | b64enc | quote }}